systemd/systemd-stable

src/journal/journald-syslog.c, src/journal/test-journal-syslog.c
Same as #15, for v237.
/cc @keszybz
=> Fix out-of-bounds read (CVE-2018-16866)

meson.build, meson_options.txt, src/basic/log.c, src/basic/log.h, src/basic/macro.h, src/basic/parse-util.c, src/basic/parse-util.h, src/basic/process-util.c, src/basic/process-util.h, src/basic/sparse-endian.h, src/basic/util.h, src/boot/efi/meson.build, src/core/dbus-execute.c, src/core/main.c, src/core/manager.h, src/core/mount.c, src/journal/test-journal-interleaving.c, src/libsystemd/sd-bus/bus-error.h, src/libudev/libudev.h, src/shared/pager.c, src/systemd/_sd-common.h, src/test/test-parse-util.c, src/udev/collect/collect.c, src/udev/udev-builtin-hwdb.c
Same as #20, for v236.
/cc @keszybz
=> Cherry-picks for build fixes, to build v236 on a modern toolchain

src/network/netdev/wireguard.c, test/test-network/conf/25-wireguard.netdev, test/test-network/systemd-networkd-tests.py
Requested in https://github.com/systemd/systemd/issues/11579#issuecomment-462314872.
=> Cherry pick Wireguard fix from #11580

NEWS, src/libsystemd/sd-device/sd-device.c, src/udev/udev-event.c, src/udev/udev-rules.c
This fixes the following upstream issues.
https://github.com/systemd/systemd/issues/11720
https://github.com/systemd/systemd/issues/11721
https://github.com/systemd/systemd/issues/11731
Also NEWS is updated.
=> v241: several fixes

src/network/networkd-address.c, src/network/networkd-link.c, src/network/networkd-link.h, src/network/networkd-route.c, src/network/networkd-route.h
networkd fixes cherry-picked from systemd/systemd@7ecf0c3, systemd/systemd@30226d2, systemd/systemd@cbff717
=> backports for v238

src/basic/path-util.h, src/basic/process-util.h, src/basic/string-util.h, src/journal/journal-send.c, src/journal/journald-audit.c, src/libsystemd-network/network-internal.c, src/libsystemd/sd-bus/bus-internal.c, src/libsystemd/sd-bus/bus-internal.h, src/libsystemd/sd-bus/bus-objects.c, src/libsystemd/sd-bus/bus-socket.c, src/libsystemd/sd-bus/sd-bus.c, src/network/netdev/netdev.c, src/nspawn/nspawn-network.c, src/resolve/resolved-dns-dnssec.c
=> V239 stable update

src/network/networkd-link.c, src/network/networkd-link.h, src/network/networkd-manager.c, src/resolve/resolved-link.c
These changes fix some networkd and resolved breackage introduced by
v242 (#12285 and #12315).
=> Backport a couple of networkd and resolved fixes

src/network/networkd-sysctl.c
This backports https://github.com/systemd/systemd/pull/18069.
=> network: fix ipv6 privacy extensions

src/network/networkd-nexthop.c, src/network/networkd-route.c, src/network/networkd-route.h, test/test-network/conf/25-nexthop.network, test/test-network/conf/25-route-static.network, test/test-network/systemd-networkd-tests.py
This backports https://github.com/systemd/systemd/pull/20498.
=> [v249] network: fix logic for checking gateway address

src/boot/efi/boot.c, src/boot/efi/console.c, src/boot/efi/console.h, src/boot/efi/random-seed.c, src/boot/efi/stub.c, src/boot/efi/util.c, src/boot/efi/util.h
=> [v249] sd-boot: fix console input handling

.github/workflows/build_test.yml, .github/workflows/cifuzz.yml, .github/workflows/mkosi.yml, .github/workflows/unit_tests.yml, .semaphore/semaphore.yml, src/oom/test-oomd-util.c
=> [v249] ci: run the unit_tests and mkosi jobs on stable branches as well

src/libsystemd-network/dhcp6-internal.h, src/libsystemd-network/dhcp6-lease-internal.h, src/libsystemd-network/dhcp6-option.c, src/libsystemd-network/sd-dhcp6-client.c, src/libsystemd-network/sd-dhcp6-lease.c, src/libsystemd-network/test-dhcp6-client.c
Fixes https://github.com/systemd/systemd/issues/20306
The last commit fixes the issue. Other commits are for solving conflicts.
=> [v249] fix dhcp6 client sntp option handling

src/basic/btrfs-util.c, src/basic/btrfs-util.h, src/basic/rm-rf.c, src/basic/rm-rf.h, src/import/export-tar.c, src/shared/machine-image.c
@mbiebl would you be able to give this a spin? I have just ran the unit tests
=> [v247] CVE-2021-3997

src/boot/efi/boot.c, src/boot/efi/meson.build, src/fundamental/meson.build
Makes the 250 build fully reproducible on Debian: https://github.com/systemd/systemd/issues/22157
=> [v250] meson fixes for systemd-boot reproducibility

.github/workflows/build_test.sh, .packit.yml, src/basic/virt.c, src/libsystemd-network/sd-dhcp-server.c, src/network/networkd-address-generation.c, src/network/networkd-address-generation.h, src/network/networkd-dhcp-prefix-delegation.c, src/network/networkd-link.c, src/network/networkd-manager.c, src/resolve/resolved-bus.c, src/resolve/resolved-varlink.c, src/shared/udev-util.c, src/shared/udev-util.h, test/test-network/systemd-networkd-tests.py
Most backports are for networkd.
Replaces #160.
=> [v250] stable backports 2022-02-23

src/network/wait-online/link.c, src/network/wait-online/manager.c, src/network/wait-online/manager.h
=> [v249] stable backports for networkd-wait-online

src/libsystemd/sd-bus/bus-introspect.c, src/libsystemd/sd-bus/bus-introspect.h, src/libsystemd/sd-bus/bus-objects.c, src/shared/bus-object.c
Otherwise, the generated xml files are not reproducible.
=> [Backport] bus: Use OrderedSet for introspection

src/journal-remote/microhttpd-util.c
Follow-up for 7fe76ec72caef21abe4b3c2a948b750652723c55.
=> [v249] journal-remote: fix build without gnutls

units/systemd-pstore.service.in
This PR cherry-picks fixes service relationship fixes in systemd-pstore.service related to systemd/systemd#18540
=> v250-stable: backport systemd-pstore.service fixes

src/core/unit.c
Allow-listing a device implicitly blocks everything else, so this has the opposite of the intended effect when PrivateDevices= is not used.
Allow-list char-rtc only if there is a device policy set.
Fixes https://github.com/systemd/systemd/issues/18142
(cherry picked from commit 63857bf4f7a5dd48a2b971d9bae2c06cc829b630)
This bugfix was never backported, and caused a later bad backport, see https://github.com/systemd/systemd/issues/26673
=> core: allow-list char-rtc with ProtectClock=yes only if needed

.github/workflows/mkosi.yml, mkosi.conf.d/centos/10-centos.conf, mkosi.conf.d/centos/mkosi.reposdir/powertools.repo
mkosi's action added it after the pin, but we can't move forward without other systemd changes
=> CI: install python3-pyelftools for mkosi job

test/TEST-26-SYSTEMCTL/test.sh
Needed by 744ea4536f6a535313a8c7f3ad2f069b51a3a933
=> test: install 'script' for TEST-26-SYSTEMCTL

hwdb.d/60-keyboard.hwdb, hwdb.d/60-sensor.hwdb
git restore -s origin/main hwdb.d/ test/hwdb.d test/hwdb-test.sh
=> hwdb: update to 2533fdd0fbe71e4a3fa7a2cca9830cd864fb9136

src/basic/virt.c
Backport of https://github.com/systemd/systemd/pull/31871
=> basic/virt: Fix virtualbox detection on proprietary system via board_vendor

src/login/logind-dbus.c, src/login/logind-dbus.h, src/login/logind-session.c, src/network/tc/qdisc.c, src/network/tc/qdisc.h, src/network/tc/tclass.c, src/network/tc/tclass.h
Two more that were tagged with `needs-stable-backport`.
=> V255 stable batch

.packit.yml
rawhide moved to 256, so stick with F40 which uses 255
=> packit: use Fedora 40 in v255-stable
