systemd/systemd-stable

src/systemctl/systemctl.c
units/systemd-initctl.service.in
units/systemd-initctl.socket

Cherry-pick compat with Sysvinit 2.89
These two patches are applied in Debian and Ubuntu.

Sysvinit 2.89

---

src/nspawn/nspawn-cgroup.c

This is a follow-up to 720f0a2f3c928cc9379501a52146be9fbb4d9be2.
See https://github.com/systemd/systemd/pull/10104
Closed https://github.com/systemd/systemd/issues/10026
Closed https://github.com/systemd/systemd/issues/9563
(cherry picked from commit 89f180201cd8c0f3ce5cb6e8dd7e2b3cbcf71527)
cc @evverx @Mic92 @poettering

nspawn: chown() the legacy hierarchy when it's used in a container

---

src/libsystemd/sd-bus/sd-bus.c
src/nspawn/nspawn.c
src/udev/udev-ctrl.c

Commit fbda85b078 ("tree-wide: use sockaddr_un_unlink() at two more places
where appropriate") was backported to stable, but it breaks
systemd-nspawn due to missing initialization of notify socket path. Also
backport commit to properly initialize it.
(cherry picked from commit 44ed5214add7b2c1048a9b8e6ca8cb99505a78eb)

tree-wide: use structured initialization for sockaddr_un

---

src/journal/journald-syslog.c
src/journal/test-journal-syslog.c

The original code didn't account for the fact that `strchr()` would match on the `'\0'` character, making it read past the end of the buffer if no non-whitespace character was present.
This bug was introduced in commit ec5ff4445cca6a which was first released in systemd v221 and later fixed in commit 8595102d3ddde6 which was released in v240, so versions in the range [v221, v240) are affected.
Also add the test cases from commit 8595102d3ddde6 check for the return value of `syslog_parse_identifier()` and will catch the condition that produced vulnerability from CVE-2018-16866.
Tested that these tests will fail if the fix for CVE-2018-16866 (the first commit in this series) is missing from the branch.
/cc @keszybz @yuwata 
*NOTE*: I'm planning to submit the same two commits to the other …

Fix out-of-bounds read (CVE-2018-16866)

---

src/network/networkd-address.c
src/network/networkd-link.c

In case networkd is restarted this prevents a removal of an already existing IP
address that would be configured using networkd. With the proposed changes the
IP address will be kept on the interface without removing. This happens only on
physical hosts or VMs since networkd handles interface configuration slightly
different in containers.

networkd: don't remove ip address

---

meson.build
meson_options.txt
src/basic/log.c
src/basic/log.h
src/basic/macro.h
src/basic/parse-util.c
src/basic/parse-util.h
src/basic/process-util.c
src/basic/process-util.h
src/basic/sparse-endian.h
src/basic/unaligned.h
src/basic/util.h
src/boot/efi/meson.build
src/core/dbus-execute.c
src/core/main.c
src/core/manager.h
src/core/mount.c
src/journal/journald-syslog.c
src/journal/test-journal-interleaving.c
src/journal/test-journal-syslog.c
src/libsystemd/sd-bus/bus-error.h
src/libudev/libudev.h
src/shared/pager.c
src/systemd/_sd-common.h
src/test/test-parse-util.c
src/udev/collect/collect.c
src/udev/udev-builtin-hwdb.c

This is a series of cherry-picks of recent commits that went in after v237 and that enable systemd to build with a more recent toolchain.
The most notable are the issue with Meson's `-Ddebug` which had to be renamed to `-Ddebug-extra`, the issue with `noreturn` which turned into `__noreturn__` and the issue with `MS_MOVE` getting multiple definitions.
These *should* be safe with the older toolchains. While they enable build with newer toolchains, older ones should still work... But I haven't really tested with those, so it's quite possible something will break... Also, at least the Meson change renaming the option (`-Ddebug-extra`) is not backwards-compatible, so it will break a build that is using it...
Some of these are unfortunately somewhat more invasive... But they've been in the …

Cherry-picks for build fixes, to build v237 on a modern toolchain

---

meson.build
meson_options.txt
src/basic/log.c
src/basic/log.h
src/basic/macro.h
src/basic/missing_syscall.h
src/basic/parse-util.c
src/basic/parse-util.h
src/basic/process-util.c
src/basic/process-util.h
src/basic/sparse-endian.h
src/basic/stdio-util.h
src/basic/util.h
src/boot/efi/meson.build
src/core/dbus-execute.c
src/core/main.c
src/core/manager.h
src/core/mount.c
src/journal/test-compress.c
src/journal/test-journal-interleaving.c
src/libsystemd/sd-bus/bus-error.h
src/libudev/libudev.h
src/shared/pager.c
src/systemd/_sd-common.h
src/test/test-parse-util.c
src/udev/collect/collect.c
src/udev/udev-builtin-hwdb.c
src/udev/udev-builtin-net_id.c

Same as #20, for v235.
This includes an additional commit to test for `lz4cat` being present, so hopefully it will also address the Semaphore failure from #22.
/cc @keszybz

Cherry-picks for build fixes, to build v235 on a modern toolchain

---

src/basic/log.c
src/basic/log.h
src/basic/macro.h
src/basic/missing_syscall.h
src/basic/parse-util.c
src/basic/parse-util.h
src/basic/process-util.c
src/basic/process-util.h
src/basic/sparse-endian.h
src/basic/stdio-util.h
src/basic/util.h
src/core/dbus-execute.c
src/core/main.c
src/core/manager.h
src/core/mount.c
src/journal/test-compress.c
src/journal/test-journal-interleaving.c
src/libsystemd/sd-bus/bus-error.h
src/libudev/libudev.h
src/shared/pager.c
src/systemd/_sd-common.h
src/udev/collect/collect.c
src/udev/udev-builtin-hwdb.c
src/udev/udev-builtin-net_id.c

Same as #20, for v233.
v233 and earlier used automake, so it won't pass Semaphore CI since that expects to use Meson/ninja instead. But locally this builds fine (with recent compilers and headers), so I think we should still merge this.
/cc @keszybz

Cherry-picks for build fixes, to build v233 on a modern toolchain (still using automake though)

---

src/basic/log.c
src/basic/log.h
src/basic/macro.h
src/basic/missing_syscall.h
src/basic/parse-util.c
src/basic/parse-util.h
src/basic/process-util.c
src/basic/process-util.h
src/basic/sparse-endian.h
src/basic/stdio-util.h
src/basic/util.h
src/core/dbus-execute.c
src/core/main.c
src/core/manager.h
src/core/mount.c
src/journal/test-compress.c
src/journal/test-journal-interleaving.c
src/libsystemd-network/sd-lldp.c
src/libsystemd/sd-bus/bus-error.h
src/libudev/libudev.h
src/shared/pager.c
src/systemd/_sd-common.h
src/udev/collect/collect.c
src/udev/udev-builtin-hwdb.c
src/udev/udev-builtin-net_id.c

Same as #20, for v232.
v233 and earlier used automake, so it won't pass Semaphore CI since that expects to use Meson/ninja instead. But locally this builds fine (with recent compilers and headers), so I think we should still merge this.
/cc @keszybz

Cherry-picks for build fixes, to build v232 on a modern toolchain (still using automake though)

---

src/network/networkd-link.c
test/test-network/systemd-networkd-tests.py

This backports https://github.com/systemd/systemd/pull/11274, which fixes https://github.com/systemd/systemd/issues/11272.
This is requested by @nfnty in https://github.com/systemd/systemd/pull/11274#issuecomment-463057405.

network: fix network crash

---

src/libsystemd/sd-bus/bus-internal.c
src/libsystemd/sd-bus/bus-internal.h
src/libsystemd/sd-bus/bus-objects.c
src/libsystemd/sd-bus/bus-socket.c

This takes the three patches from https://www.openwall.com/lists/oss-security/2019/02/18/3 .  All applied cleanly except the third, where there were conflicts from 6e9417f5b4f29938fab1eee2b5edf596cc580452 and 7ae8edcd03f74da123298330b76c3fc5425042ef.

Backport CVE-2019-6454 patches for 238

---

src/shared/install.c

This backports systemd/systemd#12053 for Fedora 30 / Fedora CoreOS.

[241] shared/install: Preserve escape characters for escaped unit names

---

src/udev/udev-event.c
src/udev/udev-node.c
src/udev/udev-node.h
src/udev/udev-rules.c
src/udev/udev.h
src/udev/udevadm-test.c

This fixes bugs introduced by 29448498c724da7ade1b5efb20d7472c1b128d2c
and d838e14515c82b05a07f2bf393cce057b45b2b53.
Previously, RUN and SECLABEL keys are stored in udev_list with its unique
flag is false. If the flag is false, then udev_list is just a linked
list and new entries are always added in the last.
So, we should use OrderedHashmap instead of Hashmap.
Fixes #11368.
(cherry picked from commit 39a15c8a8dad26deda140867f03e44a535b7bd8d)

[v241] udev: run programs in the specified order

---

src/network/networkd-link.c
src/network/networkd-route.c
src/network/networkd-route.h

In case networkd is restarted this prevents a removal of an already existing
route that would be configured using networkd. With the proposed changes the
route will be kept on the interface without removing. This happens only on
physical hosts or VMs since networkd handles interface configuration slightly
different in containers.
(cherry picked from commit 7ecf0c3e1795c08f3089752d7224fe097be4ea8e)

networkd: don't remove route

---

src/fstab-generator/fstab-generator.c

Otherwise we can end up with an ordering cycle. Since d54bab90, all
local mounts now gain a default `Before=local-fs.target` dependency.
This doesn't make sense for `/sysroot` mounts in the initrd though,
since those happen later in the boot process.
Closes: #12231
---
Backport of https://github.com/systemd/systemd/pull/12281. We'd like to get this into f30 for Fedora CoreOS.

fstab-generator: use DefaultDependencies=no for /sysroot mounts

---

src/core/execute.c
src/nspawn/nspawn-mount.c

Backport the following patches for v241-stable.
The 2 patches are coming from [flatcar-linux/systemd](https://github.com/flatcar-linux/systemd):
* Revert "nspawn: remove unnecessary mount option parsing logic"
* core: factor root_directory application out of apply_working_directory

v241 stable update: for nspawn, core, resolved

---

src/core/execute.c
src/nspawn/nspawn-mount.c

Backport the following patches for v242-stable.
The 2 patches are coming from [flatcar-linux/systemd](https://github.com/flatcar-linux/systemd):
* Revert "nspawn: remove unnecessary mount option parsing logic"
* core: factor root_directory application out of apply_working_directory

v242 stable update: for nspawn, core, resolved

---

src/basic/efivars.c

EFI variable access is nowadays subject to rate limiting by the kernel.
Thus, let's cache the results of checking them, in order to minimize how
often we access them.
Fixes: #14828

efi: cache test results of boolean EFI state functions

---

src/network/generator/network-generator.c
src/partition/makefs.c

Ran into these bugs which were fixed in systemd v245. Bugs were found on a system built from Buildroot 2020.02.

V244 stable, network-generator and makefs fixes

---

src/basic/parse-util.h
src/basic/user-util.c
src/journal-remote/journal-gatewayd.c
src/journal-remote/journal-remote-main.c
src/journal-remote/microhttpd-util.h
src/random-seed/random-seed.c
src/test/test-user-util.c

Backport fix from v275 for CVE-2020-13776 per #70
Backport downstream patches from Buildroot 2020.02.x using v244. That fix build issues with uhttpd 0.9.71 and compiling with old Sourcery toolchains.
https://git.busybox.net/buildroot/tree/package/systemd/0001-random-seed-add-missing-header-for-GRND_NONBLOCK.patch?h=2020.02.x
https://git.busybox.net/buildroot/tree/package/systemd/0001-Fix-build-with-libmicrohttpd-0.9.71.patch?h=2020.02.x

V244 stable: backport CVE-2020-13776 and downstream Buildroot patches

---

src/network/networkd-link.c

This is an equivalent commit of https://github.com/systemd/systemd/pull/17316.
@keszybz If I understand correctly, we usually only backport commits that can be simply cherry-picked. Unfortunately, my recent big PR https://github.com/systemd/systemd/pull/17240 prevents to backport fixes for networkd. What should we do in this case? If you have any better idea, then please just close this PR.
---
When peer address is set, address_compare() (or address_equal()) mostly
does not work in link_is_static_address_configured(), as an Address object
stored in a Link does not contain peer addresses. So, we need to also
compare with in_addr element for IPv4 case.
Fixes https://github.com/systemd/systemd/issues/17304.
(cherry picked from commit xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)

network: directly compare with in_addr element for IPv4 case

---

src/systemd/meson.build

In some cases it is not defined. Eg in a yocto build:
src/systemd/meson.build:61:15: ERROR: Unknown variable cxx.
(cherry picked from commit 442bc2afee6c5f731c7b3e76ccab7301703a45a7)
From: https://github.com/systemd/systemd/pull/17840

meson: check that cxx variable is set before using it

---

man/crypttab.xml
src/cryptsetup/cryptsetup.c
src/shared/cryptsetup-util.h

This commit adds support for disabling the read and write
workqueues with the new crypttab options no-read-workqueue
and no-write-workqueue. These correspond to the cryptsetup
options --perf-no_read_workqueue and --perf-no_write_workqueue
respectively.

cryptsetup: add support for workqueue options

---

src/shared/dissect-image.c

The root hash signature is auto discovered only if the root hash was specified
manually. Ensure that an auto discovered root hash is also enough.
(cherry picked from commit 90f989861e1f7fd4465a8dddd1721b54ecb3f273)
Regression introduced in v247

dissect: fix root hash signature autodiscovery

---

src/nss-resolve/nss-resolve.c

For unknown reasons, sd-bus has trouble connecting to the filtered
D-Bus system proxy exported by Flatpak and the connection to the
bus is closed during authentication. Don't mistake this for a remote
error - that was causing a hard "not found" failure rather than a fallback.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1912131 for background.

Fix nss-resolve to properly fallback in a Flatpak sandbox

---

src/basic/socket-util.h
src/libsystemd/sd-netlink/netlink-internal.h
src/libsystemd/sd-netlink/sd-netlink.c

This backport https://github.com/systemd/systemd/pull/18545 and one of https://github.com/systemd/systemd/pull/17855.
Fixes https://github.com/systemd/systemd/issues/14760.
Fixes https://github.com/systemd/systemd/issues/17232.

[v247] backport netlink fix

---

src/basic/socket-util.h
src/libsystemd/sd-netlink/netlink-internal.h
src/libsystemd/sd-netlink/sd-netlink.c

This backport https://github.com/systemd/systemd/pull/18545 and one of https://github.com/systemd/systemd/pull/17855.
Fixes https://github.com/systemd/systemd/issues/14760.
Fixes https://github.com/systemd/systemd/issues/17232.

[v246] backport netlink fix

---

src/portable/portablectl.c

Partial backport from:
https://github.com/systemd/systemd/commit/e26fe5f91158a0d9133e61347650dfb73aadd6bb
It is arguably a bug and was highlighted by a user in https://github.com/systemd/systemd/issues/18888

[246] portablectl: start/stop path/timer units too

---

src/portable/portablectl.c

Partial backport from:
https://github.com/systemd/systemd/commit/e26fe5f91158a0d9133e61347650dfb73aadd6bb
It is arguably a bug and was highlighted by a user in https://github.com/systemd/systemd/issues/18888

[247] portablectl: start/stop path/timer units too

---

src/basic/selinux-util.c

https://bugzilla.redhat.com/show_bug.cgi?id=1944171
Thread 1 (Thread 0x7fb5f0341b80 (LWP 1974)):
№0  selabel_lookup_common (rec=0x0, translating=0, key=0x55f616ac4750 "/run/user/1000/systemd/units/invocation:systemd-tmpfiles-clean.service", type=40960) at label.c:167
'rec' is the handle that we passed.
№1  0x00007fb5f13ae87f in selabel_lookup_raw (rec=<optimized out>, con=con@entry=0x7fffef307380, key=key@entry=0x55f616ac4750 "/run/user/1000/systemd/units/invocation:systemd-tmpfiles-clean.service", type=type@entry=40960) at label.c:256
lr = <optimized out>
'rec' is passed through as is to selabel_lookup_common().
№2  0x00007fb5f1561b2d in selinux_create_file_prepare_abspath (abspath=0x55f616ac4750 "/run/user/1000/systemd/units/invocation:systemd-tmpfiles-clean.service", mode=40960) at …

selinux: do not crash if policy becomes unavailable after reload

---

src/core/load-fragment.c

LoadCredentials=foo causes an assertion to be triggered, as we
are not checking that the rvalue's right hand side part is non-empty
before using it in unit_full_printf.
Fixes https://github.com/systemd/systemd/issues/19178
```
...
Assertion 'format' failed at src/core/unit-printf.c:232, function unit_full_printf(). Aborting.
Aborted (core dumped)
```

LoadCredentials: do not assert on invalid syntax

---

src/boot/efi/console.c
src/boot/efi/console.h
src/boot/efi/missing_efi.h

These were added to eficonex.h in gnu-efi 3.0.13. Let's move them
to missing_efi.h behind an appropriate guard to fix the build with
recent versions of gnu-efi.
(cherry picked from commit 95ba433a5f34baf92921fb58051bc8241f908c0e)
Backported from https://github.com/systemd/systemd/pull/18987

boot: Move console declarations to missing_efi.h

---

src/hostname/hostnamectl.c

This fixes a bug introduced by 822be62fb23ed0ec1062ffd18057e53f6c2f8c01.
Before this, if terminal width is not enough, the all subsequent lines
are included in the hyperlink.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1955475.
(cherry picked from commit 8fc1efa88fb935ab4357fa39ed71ccb70df55d7e)

hostnamectl: fix hyperlink in "Operating System" field (v248)

---

src/libsystemd/sd-netlink/rtnl-message.c
src/network/networkd-neighbor.c

We were duplicating setting flags for the message and a combination of
NLM_F_APPEND and NLM_F_CREATE which does not make sense. We should have
been using NLM_F_REPLACE and NLM_F_CREATE since the kernel can
dynamically create neighbors prior to us adding an entry. Otherwise, we
can end up with cases where the message will time out after ~25s even
though the neighbor still gets added. This delays the rest of the setup
of the interface even though the error is ultimately ignored.
(cherry picked from commit 192a9d95ea3e058afd824d38a9cea16ad0a84a57)

network: neighbor: Always add neighbors with replace (v247)

---

src/network/networkd-address.c
src/network/networkd-route.c
src/network/networkd-route.h

Fixes https://github.com/systemd/systemd/issues/20244.
(cherry picked from commit 10e417b3eac03c1bcd0b5f3d5c24291ac644e164)

[v248] network: use address_equal()/route_equal() to compare addresses or routes configured by NDisc

---

src/network/networkd-address.c
src/network/networkd-link.c
src/network/networkd-ndisc.c
src/network/networkd-route.c
test/test-network/conf/networkd-manage-foreign-routes-no.conf
test/test-network/systemd-networkd-tests.py

Fixes https://github.com/systemd/systemd/issues/20201, https://github.com/systemd/systemd/issues/20203, https://github.com/systemd/systemd/issues/20244, and https://github.com/systemd/systemd/issues/20245.

[v249] backport several networkd fixes

---

src/udev/udev-builtin-net_setup_link.c

From #20300:
> commit 70f32a260b5ebb68c19ecadf5d69b3844896ba55
> Author: Yu Watanabe <watanabe.yu+github@gmail.com>
> Date:   Sun May 23 16:59:40 2021 +0900
>     udev/net: do not manage loopback interfaces
>     There are nothing we can configure in udevd for loopback interfaces;
>     no ethertool configs can be applied, MAC address, interface name should
> introduced a regression for 'udevadm test-builtin net_setup_link /sys/class/net/lo/'.
> Prior to this commit this command would exit with 0 whereas after this commit
> it exists with 1. This causes cloud-init on Archlinux to fail as this command
> is run by it and likely also netplan to have networkd rescan and re-apply a
> bunch of things on NICs.
I think it's reasonable to keep returning 0 here: we are intentatinally doing
nothing …

udev: when setting up lo, do not return an error

---

src/network/networkd-setlink.c

Fix a bug introduced by 7558f9e717381eef0ddc8ddfb5a754ea4b0f3e6c.
Fixes https://github.com/systemd/systemd/issues/20428.
(cherry picked from commit 1e8cce8f1e61e01db844d518b7051b6ce69867fd)

[v249] network: fix configuring of CAN devices

---

man/networkd.conf.xml
src/network/networkd-gperf.gperf
src/network/networkd-manager.c
src/network/networkd-manager.h
src/network/networkd-routing-policy-rule.c
src/network/networkd.conf

This backports https://github.com/systemd/systemd/pull/19287.
This introduces a kind of new feature, but this is an important follow-up for 0b81225e5791f660506f7db0ab88078cf296b771.
See https://github.com/systemd/systemd/pull/19287#issuecomment-910906645.

[v248]: introduce ManageForeignRoutingPolicyRules= boolean setting in networkd.conf

---

man/networkd.conf.xml
src/network/networkd-gperf.gperf
src/network/networkd-manager.c
src/network/networkd-manager.h
src/network/networkd-routing-policy-rule.c
src/network/networkd.conf

This backports https://github.com/systemd/systemd/pull/19287.
This introduces a kind of new feature, but this is an important follow-up for 0b81225e5791f660506f7db0ab88078cf296b771, which is already backported to v247-stable.
See https://github.com/systemd/systemd/pull/19287#issuecomment-910906645.

[v247]: introduce ManageForeignRoutingPolicyRules= boolean setting in networkd.conf

---

src/network/networkd-routing-policy-rule.c

Fixes a bug in d94dfe7053d49fa62c4bfc07b7f3fc2227c10aff.
(cherry picked from commit 771a36439e955906290afc16a6fb3b10401892cf)

[v248] network: fix wrong flag: manage_foreign_routes -> manage_foreign_rules

---

src/coredump/coredump.c

Since 587f2a5e564cf434c2e0a653f52b8f73e86092d8, filename for
not-compressed coredump is missing from save_external_coredump, making
it write COREDUMP_FILENAME= (empty) in journal, making `coredumpctl`
report it missing but it is actually saved.
This fixes it.
(cherry picked from commit 0cfb0971f0fcd345cae76f6837d9801b6cbde407)

[249] coredump: fix filename in journal when not compressed

---

src/locale/test-keymap-util.c

Follow-up for be0cc2ce6c947aafadb3f42dba405269f670b31c.
Fixes https://github.com/systemd/systemd/pull/19670#issuecomment-965817823.
(cherry picked from commit a914901d38e01b90e21883b6a2ca1bec21997201)
Closes #140.

[v249] test: use kbd-mode-map we ship in one more test case

---

src/core/cgroup.c
src/shared/creds-util.c
src/shared/openssl-util.c
src/shared/openssl-util.h

This already [affects fedora](https://bugzilla.redhat.com/show_bug.cgi?id=2022041), let's cherry-pick https://github.com/systemd/systemd/pull/21298.
Also add patches to fix OpenSSL-3.0 deprecation warnings, because rawhide is on 3.0 already and CI fails.

Fix rawhide build & `systemd-run --user --scope`

---

src/core/unit.c

*ret_culprit should be set if ret_culprit has been passed a non-null value,
checking the previous *ret_culprit value does not make sense.
This would cause the culprit to not properly be assigned, leading to
pid1 crash when a unit could not be stopped.
Fixes: #21476
(cherry picked from commit 3da361064bf550d1818c7cd800a514326058e5f2)

[v249] unit_is_bound_by_inactive: fix return pointer check

---

src/basic/umask-util.h
src/core/namespace.c
src/nspawn/nspawn.c
src/shared/dev-setup.c
src/test/test-execute.c
src/test/test-fs-util.c
test/test-execute/exec-umask-namespace.service

On NixOS we have a special confinement mode which creates a chroot of all the individual store paths needed for the services as `BindReadOnlyPaths`. This works fine unless the services in question use a more restrictive `UMask`, which then gets applied to all the directories leading up to the mount point. We tracked this in https://github.com/NixOS/nixpkgs/issues/147599 and after this got reported in https://github.com/systemd/systemd/issues/21548, it turned out that the fix for this is already in the main branch.
In https://github.com/systemd/systemd/issues/21548#issuecomment-981067062, we got pointed to https://github.com/systemd/systemd/pull/21320 which indeed fixes our issue.
We do currently have a very limited workaround to address the issue, but it involves adding dummy `tmpfs` …

[v249] make pid1 namespace code independent of umask

---

meson.build

(cherry picked from commit 3112d756a36993900b70fbff98e69a2a43b970a8)

meson: fix cross compiling (v249-stable)

---

man/org.freedesktop.systemd1.xml
src/core/dbus-unit.c
src/core/dbus-unit.h

Backward incompatible change to avoid returning 'skipped' if a condition causes
a job activation to be skipped when using StartUnitWithFlags().
Job results are broadcasted, so it is theoretically possible that existing
software could get confused if they see this result.
(cherry picked from commit ee3ae55e7537c716530b293c91f3fb9ae22a8049)

[v250] core: do not return 'skipped' when Condition*= fail with StartUnitWithFlags()

---

src/random-seed/random-seed.c

@mweinelt pointed out that this is probably a good thing to backport.
```
If we're consuming an on-disk seed, we usually write out a new one after
consuming it. In that case, we might be at early boot and the randomness
could be rather poor, and the kernel doesn't guarantee that it'll use
the new randomness right away for us. In order to prevent the new
entropy from getting any worse, hash together the old seed and the new
seed, and replace the final bytes of the new seed with the hash output.
This way, entropy strictly increases and never regresses.
(cherry picked from commit da2862ef06f22fc8d31dafced6d2d6dc14f2ee0b)
```

[v250] random-seed: hash together old seed and new seed before writing out file

---

.packit.yml

It's targeted to the v250 branch, while the rawhide one follows
the newest upstream release, and the command line options are not
compatible

[v250] packit: build on and use Fedora 36 spec file, drop bfq patch

---

hwdb.d/70-av-production.hwdb
hwdb.d/meson.build
hwdb.d/parse_hwdb.py
src/login/70-uaccess.rules.in

This backports https://github.com/systemd/systemd/pull/22730 to systemd 250 to allow [Boatswain](https://feaneron.com/2022/03/17/boatswain-your-stream-deck-app-for-linux/) to work properly on Fedora Linux 36.
cc: @GeorgesStavracas, @cschalle

Backport udev/hwdb support for AV production controllers

---

mkosi.default.d/opensuse/10-mkosi.opensuse

[1958/1958] Generating export-dbus-interfaces with a custom command
/root/mkosi.build: line 70: groupadd: command not found
(cherry picked from commit 37b7eef35daad03c9d72222dcbfcc11dfe6dc073)

mkosi: add shadow package to SUSE Tumbleweed

---

src/boot/bootctl.c

This backports the same fix from 6e9165397faa1b546d367bdfc28dd4377a8f1d0a
in systemd upstream that we can't backport directly because that commit
introduces a new feature.

bootctl: Make sure bootctl install returns 0 on success

---

src/core/device.c

This reverts commit 75d7b5989f99125e52d5c0e5656fa1cd0fae2405.
This commit was confirmed to have introduced a regression with LUKS,
so revert it for now.
https://github.com/systemd/systemd/issues/23429
Conflicts:
src/core/device.c

Revert "core/device: ignore DEVICE_FOUND_UDEV bit on switching root"

---

src/libsystemd/sd-device/device-private.h
src/libsystemd/sd-device/sd-device.c
src/udev/udev-event.c
src/udev/udev-node.c
src/udev/udev-node.h

Cherry-pick patchset: 
https://github.com/systemd/systemd/pull/20603
https://github.com/systemd/systemd/pull/20715
The patchset affects multiple distros in virtualization environment like GCP
When NVMe device is implemented in single controller, multiple devices pattern,
without the patchset, systemd-udevd will hit a race condition and results to timeout.
Eventually system will fail to initialize after 1 min and 30 secs' timeout.

cherry-pick systemd-udevd fix into v249 stable

---

src/core/device.c
test/TEST-24-CRYPTSETUP/test.sh
test/test-functions

Closes https://github.com/systemd/systemd/issues/23208.

[v251] fix LUKS issue

---

src/analyze/analyze-security.c
test/units/testsuite-65.sh

1449b0f8a96b27 fixed seccomp arch check for the offline case,
but broke it for the normal case, as when coming from D-Bus the
list of seccomp architectures is already converted to string.
Fixes https://github.com/systemd/systemd/issues/23224
(cherry picked from commit e22f2cfa5e79135d9abf53152a292357fe807dc9)

[v250] analyze: fix crash with online security check

---

src/network/netdev/netdev.c

Otherwise, the activation policy for the netdevs are ignored.
Fixes #22593.
(cherry picked from commit 047b9991a4d0d93d0dfe3d144410c619a8b74699)

[v250] network: create stacked netdevs after the underlying link is activated

---

src/boot/efi/meson.build

Newer binutils versions currently trigger the following warnings due to
a bug in gnu-efi
on arm64:
/usr/bin/ld.bfd: warning: src/boot/efi/systemd-bootaa64.elf has a LOAD segment with RWX permissions
on amd64:
/usr/bin/ld.bfd: warning: /usr/lib/crt0-efi-x86_64.o: missing .note.GNU-stack section implies executable stack
This results in a build failure due to --fatal-warnings.
Work around this issue by suppressing those warnings until gnu-efi has
been fixed.
See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1013341
(cherry picked from commit b0e5bf0451a6bc94e6e7b2a1de668b75c63f38c8)

Do not fail EFI build with newer binutils

---

src/basic/virt.c

Commit 1b86c7c59ecc ("virt: make virtualization enum a named type") made the conversion from `if (!r)` to `if (v != VIRTUALIZATION_NONE)`.
However, the initial test was meaning "if r is null", IOW "if r IS `VIRTUALIZATION_NONE`).
The test is wrong and this can lead to false detection of the container environment (when calling `systemctl exit`).
For example, https://gitlab.freedesktop.org/whot/libevdev/-/jobs/34207974 is calling `systemctl exit 0`, and systemd terminates with the exit code `130`.
Fixing that typo makes `systemctl exit 0` returns `0`.
Fixes: 1b86c7c59ecc26efdf278f5c1c4430346021cd38.
(cherry picked from commit a91078bc57950c9b0c19fd25fb2e802409695304)
---
Backport of https://github.com/systemd/systemd/pull/25941, we need this for …

[v251 backport] virt: fix container detection

---

sysusers.d/basic.conf.in

Follow-up for 49bb7fe5f88fc35b8529d7d8dfcd4c151a9aaf1a.
Fixes an issue reported at
https://github.com/systemd/systemd/pull/26270#issuecomment-1428945403.
(cherry picked from commit 9361a712f85860ead532dba1468dbd3deef00e34)

sysusers: also add root group

---

src/basic/fd-util.h
src/libsystemd-network/sd-dhcp6-client.c
src/network/networkd-dhcp-server.c
src/network/networkd-manager.c
src/network/networkd-state-file.c
src/resolve/resolved-link.c
src/test/test-fd-util.c
src/udev/net/link-config.c

(cherry picked from commit 7b9da3861a2d27dd31c360674947005a19f3cbe7)

Revert "tree-wide: Mount file descriptors via /proc/<pid>/fd"

---

docs/FILE_DESCRIPTOR_STORE.md
man/sd_listen_fds.xml
man/sd_notify.xml
man/systemd.service.xml

And link it up everywhere.
(cherry picked from commit 0959847af5a4ee5282eb95d500899e00e33677d6)
(systemd.io is published from this repository, so get this doc backported to publish it)

doc: add a markdown doc giving an overview over the fdstore

---

src/boot/efi/boot.c

The kernel loads the DTB from EFI before ExitBootServices():
https://github.com/torvalds/linux/blob/v6.5/drivers/firmware/efi/libstub/fdt.c#L245
DTBs can map and assign arbitrary memory ranges. The kernel refuses to load one from the dtb= kernel command line parameter when secure boot is enabled, as it's not safe. Let's do the same for type 1 entries, as they are unverified.
This only affects arm64 and riscv64, firmwares do not support DTB on x86.
(cherry picked from commit 4b4d612d860a4acbbc22bc64a32637c0eb792cee) (cherry picked from commit c1404fff32d439a726e972daa34470c863465577)

boot: skip loading DTBs in type 1 when secure boot is enabled

---

src/network/networkd-json.c

Fixes a bug introduced by 0843ec6c44c7b41b14f6f32d3ee7039e5e615296.
Fixes https://github.com/systemd/systemd/issues/29145.
(In upstream, the issue is fixed by 8d3c5b39b9bbc89953d1da3e9fbff1524c952ac6).

network: fix json format for SIP servers (for v253)

---

src/kernel-install/60-ukify.install.in

Without this change, 60-ukify.install is not particularly useful as only prebuilt initrds passed to kernel-install will be used. Also, this logic is only used if `uki_generator` is explicitly set to `ukify`, so this will only be very rarely used so the change should be safe.

Backport changes to have 60-ukify.install look in the staging directory for initrds

---

test/TEST-08-INITRD/test.sh
test/knot-data/knot.conf
test/test-functions
test/units/testsuite-08.sh
test/units/testsuite-75.sh

These are all necessary to make the integration suite work in Debian CI

test fixes for v255

---

man/machine-id.xml
src/libsystemd/sd-id128/id128-util.c
src/shared/machine-id-setup.c

Backport of https://github.com/systemd/systemd/pull/31067
As this only affects new Xen VMs this should be a safe change to introduce to stable.

machine-id-setup: Generate stable machine IDs on Xen virtual machines.

---

presets/90-systemd.preset

Adding this to presets instead of making it statically installed. Enable systemd-confext and systemd-sysext service files so that extensions can be picked up automatically on OS boot

confext and sysext: enable services on OS boot

---

src/basic/missing_syscall_def.h
src/basic/missing_syscalls.py
src/shared/seccomp-util.c
src/test/test-seccomp.c

254 is the last systemd release to support split-usr, so we will have probably have some users camping on it for a bit.
These patches should help with supporting glibc 2.39 which uses fchmodat2 internally.

Backport fchmodat2 changes to 254 to support glibc 2.39

---

docs/_config.yml
src/basic/filesystems-gperf.gperf
src/basic/missing_magic.h
src/libsystemd-network/dhcp-option.c
src/libsystemd-network/dhcp-option.h
src/libsystemd-network/sd-dhcp-server.c
test/TEST-69-SHUTDOWN/test.sh
test/test-functions
test/test-shutdown.py
test/units/testsuite-04.journal.sh
test/units/testsuite-45.sh
test/units/testsuite-50.sh
test/units/testsuite-72.sh
test/units/testsuite-75.sh

As it breaks relative links to other pages. For example, the BOOT_LOADER_INTERFACE page has a relative link to
AUTOMATIC_BOOT_ASSESSMENT. With a slash in the page's permalink, that link leads to:
http://127.0.0.1:4000/BOOT_LOADER_INTERFACE/AUTOMATIC_BOOT_ASSESSMENT
which is incorrect. Dropping the trailing slash makes the link link to the correct place:
http://127.0.0.1:4000/AUTOMATIC_BOOT_ASSESSMENT
Resolves: #32088
(cherry picked from commit d1a7e030c5daa4a09ee93b8af6b28ecaac5d34d0)

docs: don't suffix page permalink with a slash

---

src/basic/virt.c

Backport of https://github.com/systemd/systemd/pull/31871

basic/virt: Fix virtualbox detection on proprietary system via board_vendor

---

src/resolve/resolved-dns-transaction.c

If we request a DS and the resolver offers an unsigned SOA, a new auxiliary transaction for the DS will be rejected as a loop, and we might not make any progress toward finding the DS we need. Let's ensure that we at least always check the parent in this case.
Fixes: 47690634f157 ("resolved: don't request the SOA for every dns label") (cherry picked from commit d840783db5208219c78d73b9b46ef5daae9fea0a)

resolved: always progress DS queries

---

src/core/core-varlink.c
src/core/manager-serialize.c

Before this PR, if m->varlink_server is not yet set up during deserialization, we call manager_setup_varlink_server rather than manager_varlink_init, the former of which doesn't setup varlink addresses, but only binds to methods. This results in that newly-added varlink addresses not getting created if deserialization takes place.
Therefore, let's switch to manager_varlink_init, and add some sanity checks to it in order to prevent listening on the same address twice.
Fixes #29373
Replaces #29421
(cherry picked from commit 6906c028e83b77b35eaaf87b27d0fe5c6e1984b7)

core/varlink: make sure we setup non-serialized varlink sockets
